[package]
name = "Encrypter"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
rand = "0.9.0"

[[bin]]
name = "encrypt"
path = "src/encrypt.rs"

[[bin]]
name = "decrypt"
path = "src/decrypt.rs"
